import { convexQuery } from "../convex-client.js";

// ============================================================
// OPERATIONS TOOLS — Dashboard, Alerts, Tasks, Briefings
// ============================================================

export const operationsTools = [
  {
    name: "inventory_dashboard",
    description:
      "Get the operational dashboard overview — a snapshot of inventory health, open alerts, pending tasks, active builds, and recent activity. This is the high-level status of everything.",
    inputSchema: {
      type: "object" as const,
      properties: {},
    },
    handler: async (_args: Record<string, unknown>) => {
      const result = await convexQuery("dashboard:overview", {});
      return result;
    },
  },

  {
    name: "inventory_list_alerts",
    description:
      'List active alerts generated by the operations agent. Includes low stock warnings, overdue POs, QC failures, and structural violations. Filter by status: "open", "acknowledged", "resolved", "dismissed".',
    inputSchema: {
      type: "object" as const,
      properties: {
        status: {
          type: "string",
          description:
            'Filter by alert status (default: "open"). Options: "open", "acknowledged", "resolved", "dismissed"',
          default: "open",
        },
        type: {
          type: "string",
          description:
            'Optional filter by type: "low_stock", "po_overdue", "qc_failure", "structure_violation", "count_needed"',
        },
        limit: {
          type: "number",
          description: "Maximum results (default: 20)",
          default: 20,
        },
      },
    },
    handler: async (args: Record<string, unknown>) => {
      const result = await convexQuery("agent/alerts:list", {
        status: args.status as string | undefined,
        type: args.type as string | undefined,
        limit: (args.limit as number) ?? 20,
      });
      return result;
    },
  },

  {
    name: "inventory_list_tasks",
    description:
      'List tasks assigned by the operations agent (the "Meat Bag Director"). Shows what needs human action — inventory counts, PO reviews, BOM updates, etc.',
    inputSchema: {
      type: "object" as const,
      properties: {
        status: {
          type: "string",
          description:
            'Filter by task status: "pending", "in_progress", "completed", "cancelled"',
        },
        priority: {
          type: "string",
          description:
            'Filter by priority: "low", "medium", "high", "urgent"',
        },
        category: {
          type: "string",
          description:
            'Filter by category: "inventory", "drive", "production", "purchasing"',
        },
        limit: {
          type: "number",
          description: "Maximum results (default: 20)",
          default: 20,
        },
      },
    },
    handler: async (args: Record<string, unknown>) => {
      const result = await convexQuery("agent/tasks:list", {
        status: args.status as string | undefined,
        priority: args.priority as string | undefined,
        category: args.category as string | undefined,
        limit: (args.limit as number) ?? 20,
      });
      return result;
    },
  },

  {
    name: "inventory_get_briefing",
    description:
      "Get today's morning operational briefing, or the most recent briefing if today's hasn't been generated yet. Contains inventory status, Drive changes, pending tasks, and upcoming items.",
    inputSchema: {
      type: "object" as const,
      properties: {
        date: {
          type: "string",
          description:
            'Specific date to get briefing for (YYYY-MM-DD format). Defaults to today.',
        },
      },
    },
    handler: async (args: Record<string, unknown>) => {
      // Try today first, fall back to latest
      const today = await convexQuery("agent/briefing:today", {});
      if (today) return today;

      const latest = await convexQuery("agent/briefing:latest", {});
      return latest ?? { message: "No briefings generated yet. The daily briefing cron runs at 7:00 AM CT." };
    },
  },

  {
    name: "inventory_bom_sync_status",
    description:
      "Check the status of the BOM sync system — recent BOM changes detected, unresolved changes needing attention, and sync health.",
    inputSchema: {
      type: "object" as const,
      properties: {
        product: {
          type: "string",
          description: "Optional: filter to a specific product",
        },
      },
    },
    handler: async (args: Record<string, unknown>) => {
      const overview = await convexQuery("agent/bomSync:syncOverview", {});
      const pending = await convexQuery("agent/bomSync:pendingChanges", {});

      let productChanges = null;
      if (args.product) {
        productChanges = await convexQuery("agent/bomSync:listChangeLogs", {
          product: args.product as string,
          limit: 10,
        });
      }

      return { overview, pending, productChanges };
    },
  },

  {
    name: "inventory_escalation_status",
    description:
      "Check the escalation engine status — how many tasks are overdue, which have been auto-escalated, and stale alerts count.",
    inputSchema: {
      type: "object" as const,
      properties: {},
    },
    handler: async (_args: Record<string, unknown>) => {
      const stats = await convexQuery("agent/escalation:stats", {});
      const recent = await convexQuery(
        "agent/escalation:recentEscalations",
        { limit: 10 }
      );
      return { stats, recentEscalations: recent };
    },
  },

  {
    name: "inventory_list_locations",
    description:
      "List warehouse locations — shelves, bins, drawers, rooms. Shows the hierarchical storage structure.",
    inputSchema: {
      type: "object" as const,
      properties: {
        parentId: {
          type: "string",
          description: "Optional: list children of a specific location",
        },
      },
    },
    handler: async (args: Record<string, unknown>) => {
      if (args.parentId) {
        const result = await convexQuery("inventory/locations:listChildren", {
          parentId: args.parentId as string,
        });
        return result;
      }
      const result = await convexQuery("inventory/locations:tree", {});
      return result;
    },
  },

  {
    name: "inventory_recent_transactions",
    description:
      "View recent inventory transactions — receives, consumes, adjustments, transfers, scraps. Full audit trail with timestamps.",
    inputSchema: {
      type: "object" as const,
      properties: {
        type: {
          type: "string",
          description:
            'Filter by transaction type: "receive", "consume", "adjust", "transfer", "return", "scrap"',
        },
        limit: {
          type: "number",
          description: "Maximum results (default: 20)",
          default: 20,
        },
      },
    },
    handler: async (args: Record<string, unknown>) => {
      const result = await convexQuery("inventory/transactions:list", {
        type: args.type as string | undefined,
        limit: (args.limit as number) ?? 20,
      });
      return result;
    },
  },
];
